"""Two-world synthetic cells — validate the frozen H1-H4 decision procedure.

Emits the full first-slice grid (color_strong / position_strong / control_strong,
D022) in the exact run_sweep contract under two hand-set ground truths:

    null      linear-probe invariance is REAL: augmentation-targeted factors sit
              at the random floor at EVERY rung. Expected: H1 refuted, H3
              confirmed, H4 sign refuted, zero verdict flips.
    artifact  linear-probe invariance is a MEASUREMENT ARTIFACT: targeted factors
              sit at the floor at the linear rung only and rise with probe
              capacity; the projector suppresses them below h. Expected: H1
              confirmed, H3 refuted, H4 sign confirmed, every targeted factor
              flips to linear_invariance_artifact.

--validate generates both worlds, runs the H1-H4 layer UNCHANGED on each, and
checks the assembled verdicts against the known ground truth — a power /
false-positive check of the frozen decision procedure before any real data.

Seed count (Q15/D025): H2's confirm rule is floor-limited — Wilcoxon's exact
two-sided minimum (2/2^n) times the assembled Holm family (~26 within-type
pairs on the first-slice grid) must clear alpha, so H2 is undecidable at n=10
(min adjusted p ~ 0.051). The sweep runs 12 seeds/cell (prereg-compliant:
frozen text says >=10): min adjusted p 0.0127, tolerant to Wilcoxon statistic
W<=2, and 1-2 gate-failed encoders still leave n >= 10. expected() derives the
H2 verdict from this floor rather than hardcoding it.

These stacks are PIPELINE-VALIDATION FIXTURES, not previews of real results:
every number below is hand-set. Output stays under results/_synthetic/
(gitignored) and every meta.json carries "synthetic_world" so tooling never
mixes these cells with real ones.

    python -m src.probes.synthetic             # emit both worlds
    python -m src.probes.synthetic --validate  # emit + verdict check (exit 1 on FAIL)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

from .instrument import RUNG_NAMES
from .ladder import LADDER, param_count

# Factor metadata mirroring src/data/{shapes3d,dsprites}.FACTORS (static copy so
# emitting fixtures needs neither h5py nor the data files).
SHAPES3D_FACTORS = (
    {"name": "floor_hue", "kind": "continuous", "index": 0, "n_values": 10, "cyclic": False},
    {"name": "wall_hue", "kind": "continuous", "index": 1, "n_values": 10, "cyclic": False},
    {"name": "object_hue", "kind": "continuous", "index": 2, "n_values": 10, "cyclic": False},
    {"name": "scale", "kind": "continuous", "index": 3, "n_values": 8, "cyclic": False},
    {"name": "shape", "kind": "categorical", "index": 4, "n_values": 4, "cyclic": False},
    {"name": "orientation", "kind": "continuous", "index": 5, "n_values": 15, "cyclic": True},
)
DSPRITES_FACTORS = (
    {"name": "shape", "kind": "categorical", "index": 1, "n_values": 3, "cyclic": False},
    {"name": "scale", "kind": "continuous", "index": 2, "n_values": 6, "cyclic": False},
    {"name": "orientation", "kind": "continuous", "index": 3, "n_values": 40, "cyclic": True},
    {"name": "pos_x", "kind": "continuous", "index": 4, "n_values": 32, "cyclic": False},
    {"name": "pos_y", "kind": "continuous", "index": 5, "n_values": 32, "cyclic": False},
)

# First-slice grid (D022) with each cell's augmentation-targeted factors.
GRID = (
    ("color", "strong", "shapes3d", SHAPES3D_FACTORS,
     ("floor_hue", "wall_hue", "object_hue")),
    ("position", "strong", "dsprites", DSPRITES_FACTORS, ("pos_x", "pos_y")),
    ("control", "strong", "shapes3d", SHAPES3D_FACTORS, ()),
)

WORLDS = ("null", "artifact")
N_SEEDS = 12        # sweep seed count (D025): H2-decidable, prereg-compliant (>=10)
BASE = 0.5          # random-encoder floor level
NOISE_FLOOR = 0.01  # per-seed floor noise
NOISE_RIDE = 0.002  # targeted-factor noise around the paired floor (null world)
G_GENUINE = {"continuous": 0.4, "categorical": 0.3}     # non-targeted factors, flat
G_ARTIFACT = (-0.01, 0.15, 0.30, 0.40)                   # per-rung G, linear -> deep
PROJ_GAP = 0.3      # artifact world: projector sits below h on targeted factors

README = """# results/_synthetic — SYNTHETIC PIPELINE-VALIDATION FIXTURES

Every stacks.npz/meta.json here is generated by `src/probes/synthetic.py` from a
HAND-SET ground truth (worlds: null / artifact). These are NOT training results
and must never be aggregated, plotted, or cited as real. Each meta.json carries
a "synthetic_world" key; real run_sweep cells never have it.
"""


def make_cell(world: str, factors, targeted, rng, n_t: int = N_SEEDS,
              n_r: int = N_SEEDS) -> dict:
    """Stacks for one cell under one world's ground truth. Axes [S, F, R]."""
    F, R = len(factors), len(RUNG_NAMES)
    random = BASE + rng.normal(0, NOISE_FLOOR, (n_r, F, R))
    trained = np.empty((n_t, F, R))
    for fi, fac in enumerate(factors):
        if fac["name"] in targeted and world == "null":
            # invariance is real: ride the seed-paired floor at every rung
            trained[:, fi] = random[np.arange(n_t) % n_r, fi] + \
                rng.normal(0, NOISE_RIDE, (n_t, R))
        elif fac["name"] in targeted:
            # artifact: at the floor under the linear rung, rising with capacity
            trained[:, fi] = BASE + np.asarray(G_ARTIFACT) + \
                rng.normal(0, NOISE_FLOOR, (n_t, R))
        else:
            trained[:, fi] = BASE + G_GENUINE[fac["kind"]] + \
                rng.normal(0, NOISE_FLOOR, (n_t, R))
    perm = rng.normal(0, NOISE_FLOOR, (n_t, F, R))  # unique-instance setting: ~0 (D018)
    projector = trained + rng.normal(0, 0.005, (n_t, F, R))
    if world == "artifact":
        for fi, fac in enumerate(factors):
            if fac["name"] in targeted:
                projector[:, fi] = trained[:, fi] - PROJ_GAP
    return {"trained": trained, "random": random, "perm": perm, "projector": projector}


def write_cell(out_root: Path, world: str, condition: str, strength: str,
               dataset: str, factors, stacks: dict, n_t: int, n_r: int) -> Path:
    """Write one cell dir in the run_sweep contract, tagged synthetic."""
    d = Path(out_root) / f"{condition}_{strength}"
    d.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(d / "stacks.npz",
                        **{k: v.astype(np.float32) for k, v in stacks.items()})

    def out_dim(f):
        return f["n_values"] if f["kind"] == "categorical" else 1

    meta = {
        "synthetic_world": world,
        "warning": "SYNTHETIC pipeline-validation fixture (src/probes/synthetic.py) "
                   "— hand-set ground truth, NOT real training results",
        "dataset": dataset,
        "condition": condition,
        "strength": strength,
        "factors": list(factors),
        "rungs": list(RUNG_NAMES),
        "rung_params_h": {f["name"]: [param_count(r, out_dim(f), 512) for r in LADDER]
                          for f in factors},
        "rung_params_projector": {f["name"]: [param_count(r, out_dim(f), 128) for r in LADDER]
                                  for f in factors},
        "projector_dim": 128,
        "seeds": {"trained": list(range(n_t)), "random": list(range(n_r))},
        "probe_train_size": 40000,
        "quality_gate": {"n_encoders": n_t, "n_passed": n_t,
                         "failed_seed_indices": [], "all_passed": True},
    }
    (d / "meta.json").write_text(json.dumps(meta, indent=2))
    return d


def emit_world(world: str, out_root: Path, n_t: int = N_SEEDS, n_r: int = N_SEEDS,
               seed: int = 0) -> Path:
    root = Path(out_root) / world
    for ci, (cond, strg, ds, factors, targeted) in enumerate(GRID):
        rng = np.random.default_rng((seed, ci, WORLDS.index(world)))
        stacks = make_cell(world, factors, targeted, rng, n_t, n_r)
        write_cell(root, world, cond, strg, ds, factors, stacks, n_t, n_r)
    return root


def emit_all(out_root: str | Path, n_t: int = N_SEEDS, n_r: int = N_SEEDS,
             seed: int = 0) -> dict:
    out_root = Path(out_root)
    out_root.mkdir(parents=True, exist_ok=True)
    (out_root / "README.md").write_text(README)
    return {w: emit_world(w, out_root, n_t, n_r, seed) for w in WORLDS}


# --- verdict check --------------------------------------------------------------

ALPHA = 0.05


def h2_floor(n_t: int, n_pairs: int) -> float:
    """Smallest POSSIBLE Holm-adjusted H2 p: Wilcoxon exact two-sided minimum
    (2/2^n) times the assembled family size. Above alpha => H2 undecidable (Q15)."""
    return n_pairs * 2.0 / 2 ** n_t


def expected(world: str, n_t: int, n_pairs: int = 26) -> dict:
    """Ground-truth verdicts per world. H1/H3/H4 follow the world's construction;
    H2 under true heterogeneity (artifact world) is confirmable only when the
    Wilcoxon x Holm floor clears alpha (Q15/D025) — refuted at n=10, confirmed
    at n>=12 on the 26-pair first-slice family."""
    h2_artifact = "confirmed" if h2_floor(n_t, n_pairs) < ALPHA else "refuted"
    return {
        "null": {"H1": "refuted", "H2": "refuted", "H3": "confirmed",
                 "H4_sign": "refuted", "flips": 0,
                 "verdict": "invariant_across_ladder"},
        "artifact": {"H1": "confirmed", "H2": h2_artifact, "H3": "refuted",
                     "H4_sign": "confirmed", "flips": 5,
                     "verdict": "linear_invariance_artifact"},
    }[world]


TARGETED_CHECK = (("color_strong", "floor_hue"), ("color_strong", "wall_hue"),
                  ("color_strong", "object_hue"), ("position_strong", "pos_x"),
                  ("position_strong", "pos_y"))


def validate_world(world: str, world_root: Path, n_boot: int = 500,
                   n_t: int = N_SEEDS) -> tuple[dict, list[str]]:
    """Run the H1-H4 layer on one world and diff verdicts against ground truth."""
    from .hypotheses import analyze_cell, assemble, discover_cells, load_cell

    results = [analyze_cell(load_cell(d), n_boot=n_boot) for d in discover_cells(world_root)]
    study = assemble(results)
    (Path(world_root) / "hypotheses.json").write_text(
        json.dumps(study, indent=2, default=lambda o: o.item() if isinstance(o, np.generic)
                   else o.tolist() if isinstance(o, np.ndarray) else str(o)))

    n_pairs = len(study["hypotheses"]["H2"]["pairs"])
    exp, fails = expected(world, n_t, n_pairs), []

    def check(name, got, want):
        if got != want:
            fails.append(f"{name}: got {got!r}, expected {want!r}")

    hs = study["hypotheses"]
    check("provisional", study["provisional"], False)
    check("H1", hs["H1"]["status"], exp["H1"])
    check("H2", hs["H2"]["status"], exp["H2"])
    check("H3", hs["H3"]["status"], exp["H3"])
    check("H4 sign", hs["H4"]["sign_component"]["status"], exp["H4_sign"])
    check("flips (primary)", study["headline_flip_count"]["primary"]["n_flips"], exp["flips"])
    check("headline complete", study["headline_contrast"]["complete"], True)
    by_cf = {(t["cell"], t["factor"]): t["verdict"] for t in study["verdict_table"]}
    for cell, factor in TARGETED_CHECK:
        check(f"verdict {cell}/{factor}", by_cf.get((cell, factor)), exp["verdict"])
    return study, fails


def validate(out_root: str | Path, n_boot: int = 500, seed: int = 0,
             n_t: int = N_SEEDS, q15_contrast: bool = True) -> bool:
    roots = emit_all(out_root, n_t=n_t, n_r=n_t, seed=seed)
    ok = True
    for world, root in roots.items():
        study, fails = validate_world(world, root, n_boot=n_boot, n_t=n_t)
        status = "PASS" if not fails else "FAIL"
        h2 = study["hypotheses"]["H2"]["status"]
        print(f"[synthetic] world={world} (n={n_t}): {status} (H2 {h2})")
        for f in fails:
            print(f"[synthetic]   MISMATCH {f}")
        ok &= not fails

    if q15_contrast and n_t != 10:
        # Q15 demonstration: same artifact ground truth at n=10 must leave H2
        # refuted — the Wilcoxon x Holm floor (~0.051) sits above alpha.
        import shutil
        import tempfile
        tmp = tempfile.mkdtemp()
        try:
            root10 = emit_world("artifact", Path(tmp), n_t=10, n_r=10, seed=seed)
            study10, fails10 = validate_world("artifact", root10, n_boot=n_boot, n_t=10)
            pairs10 = study10["hypotheses"]["H2"]["pairs"]
            min_p = min(e["p_holm"] for e in pairs10)
            floor = h2_floor(10, len(pairs10))
            print(f"[synthetic] Q15 contrast — artifact @ n=10: H2 "
                  f"{study10['hypotheses']['H2']['status']} under TRUE heterogeneity "
                  f"(min p_holm {min_p:.4f}, floor {floor:.4f} > {ALPHA}) "
                  f"-> D025: {N_SEEDS} seeds/cell "
                  f"(floor {h2_floor(N_SEEDS, len(pairs10)):.4f}).")
            ok &= not fails10
        finally:
            shutil.rmtree(tmp)

    print(f"[synthetic] decision-procedure validation: {'PASS' if ok else 'FAIL'} "
          f"(fixtures under {out_root} are SYNTHETIC — never mix with real cells)")
    return ok


def _main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out-root", default="results/_synthetic")
    ap.add_argument("--validate", action="store_true",
                    help="emit both worlds and check the H1-H4 verdicts against ground truth")
    ap.add_argument("--n-seeds", type=int, default=N_SEEDS,
                    help="trained + random seeds per cell (sweep plan: 12, D025)")
    ap.add_argument("--n-boot", type=int, default=500)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    if args.validate:
        sys.exit(0 if validate(args.out_root, n_boot=args.n_boot, seed=args.seed,
                               n_t=args.n_seeds) else 1)
    roots = emit_all(args.out_root, n_t=args.n_seeds, n_r=args.n_seeds, seed=args.seed)
    for world, root in roots.items():
        print(f"[synthetic] wrote {world} world -> {root} (SYNTHETIC fixtures)")


if __name__ == "__main__":
    _main()
